use anchor_lang::prelude::*;
use anchor_lang::ZeroCopy;
use bytemuck::Pod;
use bytemuck::Zeroable;

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Pod, Zeroable, AnchorSerialize, AnchorDeserialize, PartialEq, PartialOrd)]
pub struct ZCPubkey([u8; 32]);

// SAFETY: ZCPubkey is a plain-old-data struct, aligned and sized safely.
impl ZeroCopy for ZCPubkey {}

// SAFETY: generated by hash(b"account:ZCPubkey").to_bytes()[..8]
impl Discriminator for ZCPubkey {
    const DISCRIMINATOR: &'static [u8] = &[206, 176, 57, 172, 148, 71, 65, 149];
}

impl From<Pubkey> for ZCPubkey {
    fn from(p: Pubkey) -> Self {
        ZCPubkey(p.to_bytes())
    }
}

impl From<ZCPubkey> for Pubkey {
    fn from(z: ZCPubkey) -> Self {
        Pubkey::new_from_array(z.0)
    }
}

impl ZCPubkey {
    pub fn new_unique() -> Self {
        ZCPubkey::from(Pubkey::new_unique())
    }

    pub fn key(&self) -> Pubkey {
        Pubkey::from(self.0)
    }
}