anchor_version = "0.31.1"

[features]
seeds = false

[programs.localnet]
otcpof_amm = "HAccqG6fn1hKPG39bTmZQVXj5cbFfwEJ7YMufzLJwq1c"

[registry]
url = ""

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
